name: Keep gh-pages in sync wrt. main

on:
  pull_request:
    types: [closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git checkout gh-pages
      - run: git rebase main
      - run: git push origin gh-pages
