name: Keep gh-pages in sync wrt. main

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: git checkout --track origin/gh-pages
      - run: git rebase main
      - run: git push origin gh-pages
